FROM golang:1.25.5-alpine3.23

WORKDIR /code
RUN apk --no-cache add gcc git musl-dev openssh

COPY go.mod go.sum ./

RUN wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.42.1

COPY . /code
